apiVersion: v1
kind: Service
metadata:
  name: go-echo
  namespace: devhub-e2e-test-id-2
spec:
  type: LoadBalancer
  selector:
    app: go-echo
  ports:
    - protocol: TCP
      port: 1323
      targetPort: 1323